/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Render.RenderSurface;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;

/**
 *
 * @author T3ee
 */
public class BasicView extends javax.swing.JPanel {
    
    private RenderSurface m_pRs = null;
    private boolean initialized = false;
    private BasicView view = null;
    private JFXPanel fxPanel = null;
    /**
     * Creates new form BasicView
     */
    public BasicView() {
        initComponents();
        view = this;
        fxPanel = new JFXPanel();
        view.add(fxPanel);        
        Platform.runLater(new Runnable(){
            @Override
            public void run() {
                m_pRs = new RenderSurface(view.getWidth(), view.getHeight());
                m_pRs.Ref();
                Platform.setImplicitExit(false);
                fxPanel.setScene(m_pRs.GetRootScene());
                initialized = true;
            }            
        });        
    }

    public boolean isInitialized() {
        return initialized;
    }
    
    public RenderSurface GetRenderSurface(){
        return m_pRs;
    }
    
    public void UpdateSize(){
        if(initialized){
            Platform.runLater(new Runnable(){
                @Override
                public void run() {
                    m_pRs.Resize(view.getWidth(), view.getHeight());                    
                }            
            });  
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        if(initialized){
            Platform.runLater(new Runnable(){
                @Override
                public void run() {
                    m_pRs.Resize(view.getWidth(), view.getHeight());                    
                }            
            });  
        }        
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
